version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: synco_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: synco_db
      MYSQL_USER: synco
      MYSQL_PASSWORD: synco_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
